### ISSUE TITLE
wallpaperboard | Wallpapers menu customization 

### ISSUE THREAD

**Issue by besidesordinary** [danimahardhika/wallpaperboard#76]
@danimahardhika The previous versions of the wallpaperboard had a gridview displayed when you launched the app. Now in the 1.5.6 update there are different view options available such as categories and a list dropdown menu. Can we manipulate the order of the different views?

**Comment by besidesordinary** [comment]
How can you change the view order of the Wallpapers section.
For an example. Can we display the 3 given aspects in a different order like:

Wallpapers Grid view | Wallpapers Categories | Wallpapers Dropdown Menu

**Comment by danimahardhika** [comment]
@besidesordinary Let me explain first. With latest release there are 3 tabs, Latest Wallpapers, Wallpapers, and Categories.

Latest Wallpapers should be shown first, why? Because it will automatically check for new wallpapers and put in there. Each time you open the app, you will notice left tab (Latest wallpapers) will shown loading progress. If you swipe to left, navigate to wallpapers tab, you will also notice wallpapers tab already loaded, no loading progress.

**Comment by besidesordinary** [comment]
@danimahardhika Yes I understand the functionality of each tab, thank you for taking time to explain them even more. I am just curious as to know how the entire menu has been created, more precisely which part of the code is allocated for each of them, Latest Wallpapers, Wallpapers and Categories. Just want to learn how to do it myself if I were to use that feature of wallpaperboard for another app.
